
name: Midterm

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  DEVELOPMENT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a script
        run: echo "This is the development environment"
   
  TESTING:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: testing
    needs: DEVELOPMENT

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a script
        run: echo "The job is running in the testing environment"
  
  PRODUCTION:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production environment
    needs: TESTING

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a script
        run: echo "The job is running in the production environment"

